# -*- coding: utf-8 -*-
"""text generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FPaNGM20YH1fUQR2jLqDwnDbWoLnIjMC
"""

docs = """ Artificial intelligence is the smart work
 From self-driving cars to voice assistants, AI systems are becoming an essentialpart of our daily lives
 These machines can analyze massive amounts of data, recognizepatterns, and make decisions faster than humans?
 Deep learning and neural networks haveallowed computers to learn complex relationships and improve over time
 In healthcare, AI helps doctors detect diseases early and suggest better treatment plans
 In education,intelligent systems assist students by adapting lessons to their learning pace.
 Businesses use predictive algorithms to forecast sales and understand customer behavior
 These are results for what is ml
Search instead for wehta is ml
AI Overview
"ML" can stand for both machine learning and milliliter, depending on the context. Machine learning is a field of artificial intelligence where computer systems learn from data to make predictions or decisions. A milliliter is a metric unit of volume, equal to one-thousandth of a liter.
Machine learning (ML)
A subset of AI where algorithms are trained on data to find patterns, make predictions, and improve their performance over time without explicit programming.
Examples include predicting future trends, recommending songs, or identifying objects in images.
It is the technology behind things like translation apps and autonomous vehicles.
Milliliter (ml)
 Natural language processing enables chatbots to understand and respond to people just like humans
 Machine learning models continue to evolve becoming more accurate and efficient
 As technology advances, ethical challenges such as data privacy and fairness must also be addressed
 The goal of artificial intelligence is not to replace humans but to enhance their capabilities.
 The future will depend on how responsibly we design, train, and use these intelligent systems
 AI is more than just a tool; it is a revolutionary step toward a smarter and more connected world where machines and humans work together in harmony
 These are results for what is ml
Search instead for wehta is ml
AI Overview
"ML" can stand for both machine learning and milliliter, depending on the context. Machine learning is a field of artificial intelligence where computer systems learn from data to make predictions or decisions. A milliliter is a metric unit of volume, equal to one-thousandth of a liter.
Machine learning (ML)
A subset of AI where algorithms are trained on data to find patterns, make predictions, and improve their performance over time without explicit programming.
Examples include predicting future trends, recommending songs, or identifying objects in images.
It is the technology behind things like translation apps and autonomous vehicles.
Milliliter (ml)

Machine learning (ML) is a way to train software, called a model, to make predictions or generate content using data.

ML systems can be categorized as supervised, unsupervised, reinforcement, or generative AI, each learning differently.

Supervised learning uses labeled data to make predictions, often for regression (predicting numerical values) or classification (categorizing data).

Unsupervised learning identifies patterns in unlabeled data, commonly using clustering to group similar data points.

Generative AI creates new content, such as text, images, or music, by learning patterns from existing data and mimicking them.


Machine learning (ML) powers some of the most important technologies we use, from translation apps to autonomous vehicles. This course explains the core concepts behind ML.

ML offers a new way to solve problems, answer complex questions, and create new content. ML can predict the weather, estimate travel times, recommend songs, auto-complete sentences, summarize articles, and generate nev

"""

import tensorflow
from tensorflow.keras.preprocessing.text import Tokenizer

tokenize = Tokenizer()

tokenize.fit_on_texts([docs])

tokenize.word_index

sent = []
for sentence in docs.split('\n'):
  tokenized_sentence = tokenize.texts_to_sequences([sentence])[0]

  for i in range(1, len(tokenized_sentence)):
    sent.append(tokenized_sentence[:i+1])

max_l = max([len(x) for x in sent])
max_l

from tensorflow.keras.preprocessing.sequence import pad_sequences
pad_sequence = pad_sequences(sent,maxlen=max_l,padding = "pre")

pad_sequence

X = pad_sequence[:,:-1]

y = pad_sequence[:,-1]

X.shape

y.shape

from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes = 134)

X.shape

y.shape

import numpy as np
y = np.array(y)

from tensorflow import  keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Embedding(input_dim=134, output_dim=80, input_length=max_l),
    layers.LSTM(150, activation="relu"),
    layers.Dense(134,activation="softmax")
])

model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=['accuracy'])

history =model.fit(X,y , epochs = 100)

import matplotlib.pyplot as plt
plt.plot(history.history['accuracy'],label = "accuracy")
plt.plot(history.history['val_accuracy'],label = "val_accuracy")
plt.title("Accuracy and val_accuracy")
plt.show()

import matplotlib.pyplot as plt
plt.plot(history.history['loss'],label = "loss")
plt.plot(history.history['val_loss'],label = "val_loss")
plt.title("loss and val_loss")
plt.show()

# prediction

# tokenize
import time
text = "Businesses"
for i in range(10):
  tok = tokenize.texts_to_sequences([text])[0]
  # padding
  pred_token_pad = pad_sequences([tok], maxlen=max_l,padding="pre")
 # model predict
  pos = np.argmax(model.predict(pred_token_pad))
  for word,index in tokenize.word_index.items():
    if index == pos:
      text = text +" "+ word
      print(text)
      time.sleep(1)





